name: 'pylint pytest'
description: 'run pylint and pytest with coverage if possible'
inputs:
  module_name:
    description: 'name of the python module in the repository'
    required: true
    default: 'NOT_SET'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "${{ inputs.module_name }}"
    - shell: bash
      run: ls -al
    - run: python -m pip install --upgrade pip
      shell: bash
    - run: echo "{PYTHON_VERSION}={`python -c 'import sys; print(sys.version_info[0])'`}" >> $GITHUB_ENV
      shell: bash
    - run: echo "$PYTHON_VERSION"
      shell: bash
    - run: if [ "$PYTHON_VERSION" == "2" ]; then pip install pytest pytest-cov pylint lazy-object-proxy==1.6.0; else pip install pytest pytest-cov pylint; fi
      shell: bash
    - run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash
    - run: if [ -f requirements_test.txt ]; then pip install -r requirements_test.txt; fi
      shell: bash
    - run: pylint --rcfile=.pylintrc ${{ inputs.module_name }} || exit 0
      shell: bash
    - run: if [ -d tests -o -d test  ]; then export PYTHONPATH=$(pwd) && pytest --cov=${{ inputs.module_name }} -v; else echo "tests not found" && exit 0; fi
      shell: bash
